export const FETCH_DB_POST_REQUEST = "FETCH_DB_POST_REQUEST";
export const FETCH_DB_POST_SUCCESS = "FETCH_DB_POST_SUCCESS";
export const REMOVE_DB_POST_REQUEST = "REMOVE_DB_POST_REQUEST";
export const REMOVE_DB_POST_SUCCESS = "REMOVE_DB_POST_SUCCESS";
export const ADD_COMMENT_POST_REQUEST = "ADD_COMMENT_POST_REQUEST";
export const ADD_COMMENT_POST_SUCCESS = "ADD_COMMENT_POST_SUCCESS";
export const REMOVE_COMMENT_POST_REQUEST = "REMOVE_COMMENT_POST_REQUEST";
export const REMOVE_COMMENT_POST_SUCCESS = "REMOVE_COMMENT_POST_SUCCESS";
